# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Blog
tagline:             Rodrigo Juarez
url:                 http://rodrigojuarez.xyz/
paginate:            1
baseurl:             "http://rodrigojuarez.xyz"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rodrigo Juarez
  url:               https://twitter.com/_rodrijuarez
  email:             rodrigo.juarez.inf@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rodrijuarez/blog
